### ISSUE TITLE
Nuclear Siren takes a while to play the sound

### ISSUE THREAD

**Issue by hideki2k02** [Orvngex/OrvngeAlarmsMod#2]
Minecraft Version: 1.12.2
Forge Version: 14.23.5.2847
Mod Version: 2.1

I downloaded this mod to use the Nuclear Siren on my Draconic Fusion Reactor, but for some reason the Nuclear Siren takes a while to start playing the sound (Other Sirens play the sound as soon as there is a Redstone Signal).

**Comment by Orvngex** [comment]
After placing the siren down, try waiting about 20 seconds before using it. After that it should work no problem. It shouldn't do that anyway but let me know if that works.

**Comment by hideki2k02** [comment]
Well its an odd fix, but it worked! Thanks for the fast reply and for the solution!

Also here is an suggestion in the topic of Reactors and Dangerous stuff: Re-add the Warning System Siren as a permanent variant of the Broadcast System (the message is permanent), and make it so that the message appears on screen instead of the chat.
